name: build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Configure and build project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true

  release-msvc:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Configure and build project
        uses: threeal/cmake-action@v1.3.0
        with:
          cxx-compiler: cl
          run-build: true

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install requirements
        run: pip3 install -r docs/requirements.txt

      - name: Build with Sphinx
        run: sphinx-build -b html docs build/docs -W --keep-going

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.0
        with:
          path: build/docs
