name: build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [error]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Configure and build this project
        uses: threeal/cmake-action@v1.1.0
        with:
          source-dir: ${{ matrix.package }}
          build-dir: ${{ matrix.package }}/build
