name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-project:
    name: Build Project
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0

      - name: Build Project
        run: cmake --build build --config Release

      - name: Install Project
        run: cmake --install build --prefix install

      - name: Upload Project
        uses: actions/upload-artifact@v4.3.1
        with:
          name: package-${{ matrix.os }}
          path: install

  build-examples:
    name: Build Examples
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0
        with:
          options: BUILD_EXAMPLES=ON

      - name: Build Examples
        run: cmake --build build --target examples

  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0
        with:
          options: BUILD_DOCS=ON

      - name: Build Documentation
        run: cmake --build build --target docs

      - name: Upload Documentation
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: build/docs/html
