name: deploy
on:
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install requirements
        run: pip3 install -r docs/requirements.txt

      - name: Setup Pages
        uses: actions/configure-pages@v4.0.0

      - name: Build with Sphinx
        run: sphinx-build -b html docs docs/build -W --keep-going

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: docs/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.0
