name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  deploy-pages:
    name: Deploy Pages
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: true
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4.0.0

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0
        with:
          options: BUILD_DOCS=ON

      - name: Build Documentation
        run: cmake --build build --target docs

      - name: Upload Documentation
        uses: actions/upload-pages-artifact@v3.0.0
        with:
          path: build/docs/html

      - name: Deploy Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4.0.2
