name: test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [error]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Configure, build, and test this project
        uses: threeal/cmake-action@v1.1.0
        with:
          source-dir: ${{ matrix.package }}
          build-dir: ${{ matrix.package }}/build
          args: -DBUILD_TESTING=ON
          run-test: true

      - name: Check code coverage
        uses: threeal/gcovr-action@main
        with:
          root: ${{ matrix.package }}
          excludes: |
            ${{ matrix.package }}/build/*
            ${{ matrix.package }}/test/*
          fail-under-line: 100

  check-warning:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [error]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Configure and build this project
        uses: threeal/cmake-action@v1.1.0
        with:
          source-dir: ${{ matrix.package }}
          build-dir: ${{ matrix.package }}/build
          cxx-flags: -Werror
          args: -DBUILD_TESTING=ON

  check-formatting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [error]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Install cmake-format
        run: pip3 install cmake-format

      - name: Configure CMake
        run: cmake ${{ matrix.package }} -B ${{ matrix.package }}/build

      - name: Check code formatting
        run: |
          cmake --build ${{ matrix.package }}/build --target format
          cmake --build ${{ matrix.package }}/build --target check-format
