name: test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Configure, build, and test this project
        uses: threeal/cmake-action@v1.1.0
        with:
          source-dir: example
          build-dir: example/build
          args: -DBUILD_TESTING=ON
          run-test: true

      - name: Check code coverage
        uses: threeal/gcovr-action@main
        with:
          root: example
          excludes: |
            example/build/*
            example/test/*
          fail-under-line: 80

  check-warning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Configure and build this project
        uses: threeal/cmake-action@v1.1.0
        with:
          source-dir: example
          build-dir: example/build
          cxx-flags: -Werror
          args: -DBUILD_TESTING=ON

  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Install cmake-format
        run: pip3 install cmake-format

      - name: Configure CMake
        run: cmake example -B example/build

      - name: Check code formatting
        run: |
          cmake --build example/build --target format
          cmake --build example/build --target check-format
